# -*- coding: utf-8 -*-
"""Lab4_Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nv9Tf8ctLRiux_RUhl7izcKYRXQfQ84T
"""

# Q1

import string

d_book = dict()
iof = open("book.txt")
for line in iof:
  for word in line.split():
    word = word.strip(string.punctuation + string.whitespace)
    word = word.lower()
    if word in d_book:
      d_book[word] = d_book[word] +1
    else:
      d_book[word] = 1

d_file = dict()
iof2 = open("extra.txt")
for line in iof2:
  for word in line.split():
    word = word.strip(string.punctuation + string.whitespace)
    word = word.lower()
    if word in d_file:
      d_file[word] = d_file[word] +1
    else:
      d_file[word] = 1

counter = 0
for key in d_book:
  if key not in d_file:
    print(key)
  else:
    counter = counter + 1

print("total number of the book words available at extra file is :  ", counter)
print("total number of the words in book, which are not available in exrea file is: ", len(d_book) - counter)